FROM repoweb-microsrv.intra.fazenda.sp.gov.br:5000/dotnet/aspnet:3.1-alpine
WORKDIR /var/wwroot/modelo_core_mvc
EXPOSE 80
EXPOSE 443
COPY . .
COPY CA.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates
ENTRYPOINT ["dotnet", "modelo_core_mvc.dll"]