FROM repo-microsrv.intra.fazenda.sp.gov.br:5000/dotnet/aspnet:3.1
WORKDIR /var/wwroot/modelo_core_mvc
EXPOSE 80
EXPOSE 443
COPY . .
COPY CA.crt /etc/ssl/certs/CA.crt
RUN c_rehash /etc/ssl/cert 
RUN update-ca-certificates
ENTRYPOINT ["dotnet", "modelo_core_mvc.dll"]